<a href="https://colab.research.google.com/github/BurnTheBunsen/pytorch-deep-learning-test/blob/main/PyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Sat Oct 18 11:31:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
# Putting tensors (and models) on the GPU
# Default is on the CPU
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
tensor = torch.tensor([1, 2, 3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
tensor_on_cpu = tensor.to(device="cpu")
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

Now we do this because numpy doesnt run on cuda so we need to be readily available for numpy as well.

In [8]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [9]:
tensor_back_on_cpu.numpy()

array([1, 2, 3])

Now let the exercises begin!


In [13]:
# random_tensor_1 = torch.rand(7, 7)
# random_tensor_2 = torch.rand(1,7)
# random_tensor_1, random_tensor_2

(tensor([[0.3975, 0.3414, 0.6872, 0.8926, 0.2473, 0.7082, 0.8151],
         [0.3753, 0.6937, 0.7389, 0.0519, 0.3012, 0.8568, 0.2792],
         [0.5138, 0.4678, 0.4951, 0.9606, 0.1716, 0.3557, 0.6241],
         [0.6141, 0.2163, 0.1340, 0.9132, 0.3873, 0.7920, 0.9021],
         [0.5884, 0.7460, 0.1039, 0.0780, 0.2617, 0.3606, 0.9478],
         [0.9017, 0.1944, 0.8227, 0.0662, 0.1358, 0.2735, 0.4489],
         [0.9021, 0.9869, 0.6968, 0.0206, 0.1538, 0.8259, 0.0678]]),
 tensor([[0.1266, 0.4792, 0.8429, 0.7454, 0.3117, 0.8707, 0.4714]]))

In [16]:
# random_tensor_3 = torch.matmul(random_tensor_1, random_tensor_2.T)
# random_tensor_3

tensor([[2.5365],
        [2.0129],
        [2.0800],
        [2.2107],
        [1.4200],
        [1.4421],
        [1.9889]])

In [20]:
# RANDOM_SEED = 69
# torch.random.manual_seed(RANDOM_SEED)
# random_tensor_1 = torch.rand(7, 7)
# torch.random.manual_seed(RANDOM_SEED)
# random_tensor_2 = torch.rand(1,7)
# random_tensor_3 = torch.matmul(random_tensor_1, random_tensor_2.T)
# random_tensor_3


tensor([[2.2644],
        [1.7081],
        [1.5688],
        [2.1016],
        [2.1328],
        [1.6736],
        [1.5506]])

In [48]:
### No.5
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(size=(7,7), device="cuda")
torch.cuda.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(size=(1,7), device="cuda")
tensor_3 = torch.matmul(tensor_1, tensor_2.T)
tensor_3

tensor([[2.5893],
        [2.1242],
        [1.8872],
        [2.5468],
        [1.7516],
        [1.6445],
        [1.6517]], device='cuda:0')